const mongoose = require('mongoose');

const MONGODB_URI = 'mongodb://localhost:27017/ai_interviewer';

const questionSchema = new mongoose.Schema({
  title: { type: String, required: true, trim: true },
  description: { type: String, required: true },
  topic: { type: String, required: true },
  difficulty: { type: String, enum: ['Easy', 'Medium', 'Hard'], required: true },
  tags: [{ type: String, trim: true }],
  examples: [{ input: String, output: String, explanation: String }],
  constraints: [String],
  hints: [String],
  companies: [String],
  leetcodeLink: { type: String, default: '' },
  customTopic: { type: String, default: '' },
}, { timestamps: true });

const Question = mongoose.model('Question', questionSchema);

const questions = [

  // ==================== OOP QUESTIONS ====================

  {
    title: 'What is Object-Oriented Programming (OOP)?',
    description: 'OOP is a programming paradigm that uses "objects" — instances of classes — to model real-world entities. It organizes code by bundling data and behavior (functions) together. Popular OOP languages include Java, Python, C++, and C#. Explain the core idea behind OOP and why it is widely used.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['OOP', 'basics', 'paradigm'],
    examples: [],
    constraints: [],
    hints: ['Think about how real-world objects have properties and behaviors', 'OOP maps code to real world entities'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Infosys', 'TCS'],
    leetcodeLink: '',
  },
  {
    title: 'What are the four main principles of OOP?',
    description: 'There are four core pillars of Object-Oriented Programming: Encapsulation (bundling data with methods), Abstraction (hiding internal details), Inheritance (reusing code from parent classes), and Polymorphism (using one interface for many forms). Explain each principle with examples.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['OOP', 'pillars', 'encapsulation', 'abstraction', 'inheritance', 'polymorphism'],
    examples: [],
    constraints: [],
    hints: ['Remember the acronym A-PIE: Abstraction, Polymorphism, Inheritance, Encapsulation'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta', 'Wipro'],
    leetcodeLink: '',
  },
  {
    title: 'Define Class and Object in OOP',
    description: 'A Class is a blueprint or template for creating objects (e.g., Car, Person). An Object is a real instance of a class with specific data and behavior. For example, if Car is a class, then my_car = Car("Toyota") creates an object. Explain the difference between a class and an object with a real-world analogy.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['class', 'object', 'instance', 'OOP'],
    examples: [{ input: 'class Car with brand attribute', output: 'my_car = Car("Toyota") is an object', explanation: 'Class is the blueprint, object is the actual instance' }],
    constraints: [],
    hints: ['Think of class as a cookie cutter and object as the cookie'],
    companies: ['Amazon', 'Infosys', 'TCS', 'Wipro'],
    leetcodeLink: '',
  },
  {
    title: 'What is the difference between Class and Structure?',
    description: 'In C++, a class has members that are private by default while a structure has members that are public by default. Classes support full OOP features while structs are more lightweight. In modern languages like C#, both are similar but structs are value types while classes are reference types. Explain these differences in detail.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['class', 'struct', 'C++', 'C#'],
    examples: [],
    constraints: [],
    hints: ['Focus on default access modifiers and memory allocation differences'],
    companies: ['Microsoft', 'Google', 'Samsung'],
    leetcodeLink: '',
  },
  {
    title: 'What is Encapsulation?',
    description: 'Encapsulation means hiding the internal state and requiring all interaction through methods. It improves security and control over data. Private variables are accessed and modified only through public getter and setter methods. This ensures data integrity and prevents unauthorized access.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['encapsulation', 'private', 'getter', 'setter'],
    examples: [{ input: 'class Account with __balance = 0 (private)', output: 'Access via deposit() and withdraw() methods', explanation: 'Balance cannot be directly modified from outside' }],
    constraints: [],
    hints: ['Think of encapsulation as a capsule protecting its contents'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Flipkart'],
    leetcodeLink: '',
  },
  {
    title: 'What is Abstraction in OOP?',
    description: 'Abstraction means exposing only relevant information while hiding complexity. It focuses on what an object does, not how it does it. For example, you can use print() without knowing how it sends text to the screen. Abstract classes and interfaces are used to achieve abstraction in OOP languages.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['abstraction', 'abstract class', 'interface', 'hiding'],
    examples: [{ input: 'Using print("Hello")', output: 'Hello', explanation: 'User does not need to know how print works internally' }],
    constraints: [],
    hints: ['Abstraction hides the HOW and shows only the WHAT'],
    companies: ['Amazon', 'Microsoft', 'Infosys'],
    leetcodeLink: '',
  },
  {
    title: 'What is Inheritance in OOP?',
    description: 'Inheritance allows a class (child) to acquire properties and behaviors of another class (parent). It reduces redundancy and promotes code reuse. The child class can override or extend the behavior of the parent class. This is one of the most powerful features of OOP.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['inheritance', 'parent class', 'child class', 'reuse'],
    examples: [{ input: 'class Dog(Animal)', output: 'Dog inherits speak() from Animal', explanation: 'Dog does not need to redefine speak() method' }],
    constraints: [],
    hints: ['Think of inheritance like a child inheriting traits from parents'],
    companies: ['Google', 'Amazon', 'TCS', 'Wipro'],
    leetcodeLink: '',
  },
  {
    title: 'What is Polymorphism and its types?',
    description: 'Polymorphism means "many forms". The same function name or operator can behave differently based on context. There are two types: Compile-time (Static) polymorphism achieved through method overloading and operator overloading, and Run-time (Dynamic) polymorphism achieved through method overriding via inheritance.',
    topic: 'OOP',
    difficulty: 'Medium',
    tags: ['polymorphism', 'overloading', 'overriding', 'compile-time', 'runtime'],
    examples: [{ input: '+ operator', output: '2+3=5 or "Hello"+"World"="HelloWorld"', explanation: 'Same operator behaves differently based on operand types' }],
    constraints: [],
    hints: ['Compile-time = decided at compile time, Runtime = decided during execution'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta'],
    leetcodeLink: '',
  },
  {
    title: 'What is Method Overloading?',
    description: 'Method overloading means defining multiple methods with the same name but different parameters. It is a type of compile-time polymorphism. It is supported natively in Java and C++ but not in Python (Python uses default arguments). The compiler decides which method to call based on the arguments passed.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['overloading', 'compile-time polymorphism', 'Java', 'C++'],
    examples: [{ input: 'void greet() and void greet(String name)', output: 'Two different methods with same name', explanation: 'Called based on number/type of arguments' }],
    constraints: [],
    hints: ['Overloading = same name, different parameters, same class'],
    companies: ['Amazon', 'Microsoft', 'Infosys'],
    leetcodeLink: '',
  },
  {
    title: 'What is Method Overriding?',
    description: 'Method overriding allows a subclass to provide a specific implementation of a method already defined in its superclass. It is a type of runtime polymorphism. The method in the child class must have the same name, return type, and parameters as the method in the parent class.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['overriding', 'runtime polymorphism', 'inheritance', 'subclass'],
    examples: [{ input: 'Animal.sound() prints "Animal sound"', output: 'Dog.sound() prints "Bark"', explanation: 'Dog overrides the sound() method from Animal' }],
    constraints: [],
    hints: ['Overriding = same name, same parameters, different classes (parent-child)'],
    companies: ['Google', 'Amazon', 'TCS'],
    leetcodeLink: '',
  },
  {
    title: 'What is a Constructor and its types?',
    description: 'A constructor is a special method used to initialize objects. It has the same name as the class and no return type. It runs automatically when an object is created. Types include: Default Constructor (no parameters), Parameterized Constructor (takes arguments), and Copy Constructor in C++ (copies data from another object).',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['constructor', 'default constructor', 'parameterized', 'copy constructor'],
    examples: [{ input: 'new Car("Toyota")', output: 'Car object with brand = Toyota created', explanation: 'Parameterized constructor sets brand at creation time' }],
    constraints: [],
    hints: ['Constructor is called automatically when object is created'],
    companies: ['Microsoft', 'Amazon', 'Infosys', 'Wipro'],
    leetcodeLink: '',
  },
  {
    title: 'What is a Destructor?',
    description: 'A destructor is used in C++ to clean up memory and resources when an object is destroyed. It has the same name as the class preceded by a tilde (~). In Java, the finalize() method was used (now deprecated). Java uses garbage collection instead for automatic memory management.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['destructor', 'memory management', 'C++', 'Java', 'garbage collection'],
    examples: [],
    constraints: [],
    hints: ['Destructor is the opposite of constructor — it cleans up resources'],
    companies: ['Microsoft', 'Google', 'Samsung'],
    leetcodeLink: '',
  },
  {
    title: 'Difference between Abstract Class and Interface',
    description: 'Abstract Class can have both implemented and abstract methods, supports single inheritance, and is used for partial abstraction. Interface can only have method declarations (until Java 8), supports multiple inheritance, and is used for full abstraction. A class can implement multiple interfaces but can extend only one abstract class.',
    topic: 'OOP',
    difficulty: 'Medium',
    tags: ['abstract class', 'interface', 'inheritance', 'abstraction'],
    examples: [{ input: 'interface Drivable vs abstract class Vehicle', output: 'Interface defines capability, abstract class defines shared structure', explanation: 'Use interface for contract, abstract class for shared behavior' }],
    constraints: [],
    hints: ['Interface = full abstraction, Abstract class = partial abstraction'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta', 'Flipkart'],
    leetcodeLink: '',
  },
  {
    title: 'What is the super keyword?',
    description: 'The super keyword is used to refer to the parent class. It can be used to access the parent class constructor using super(), call a parent class method using super.methodName(), and access parent class variables. It is commonly used in method overriding to call the parent version of a method.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['super', 'parent class', 'inheritance', 'keyword'],
    examples: [{ input: 'super() in child constructor', output: 'Calls parent class constructor', explanation: 'Initializes parent class portion of the object' }],
    constraints: [],
    hints: ['super() must be the first statement in a child constructor in Java'],
    companies: ['Amazon', 'Infosys', 'TCS'],
    leetcodeLink: '',
  },
  {
    title: 'What is the this keyword?',
    description: 'The this keyword refers to the current class instance. It is useful when local and instance variables have the same name. It can also be used to call another constructor in the same class, pass the current object as an argument, and return the current object.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['this', 'current instance', 'keyword', 'Java'],
    examples: [{ input: 'this.name = name inside constructor', output: 'Distinguishes instance variable from parameter', explanation: 'this.name is instance variable, name is parameter' }],
    constraints: [],
    hints: ['this refers to the current object being constructed or modified'],
    companies: ['Amazon', 'Microsoft', 'Infosys'],
    leetcodeLink: '',
  },
  {
    title: 'What are Static Members in OOP?',
    description: 'Static members belong to the class, not to individual objects. A static variable is shared across all instances of the class. A static method can be called without creating an object. Static members are initialized when the class is loaded and are accessed using the class name rather than an object reference.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['static', 'class variable', 'static method', 'shared'],
    examples: [{ input: 'ClassName.staticMethod()', output: 'Calls method without creating object', explanation: 'No need to instantiate to call static methods' }],
    constraints: [],
    hints: ['Static = belongs to class, not instance'],
    companies: ['Google', 'Amazon', 'Microsoft'],
    leetcodeLink: '',
  },
  {
    title: 'What is a Singleton Class?',
    description: 'A singleton class allows only one instance to be created throughout the application. It ensures a shared resource like a config manager or database connection is reused. It uses a private constructor and a static method to return the single instance. It is a common design pattern in software engineering.',
    topic: 'OOP',
    difficulty: 'Medium',
    tags: ['singleton', 'design pattern', 'instance', 'private constructor'],
    examples: [{ input: 'Singleton.getInstance()', output: 'Always returns the same instance', explanation: 'Only one object exists throughout the application lifecycle' }],
    constraints: [],
    hints: ['Private constructor prevents outside instantiation'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta'],
    leetcodeLink: '',
  },
  {
    title: 'What are Access Specifiers in OOP?',
    description: 'Access specifiers control the visibility of class members. Public members are accessible everywhere. Private members are accessible only inside the class. Protected members are accessible inside the class and its subclasses. Default (package-private in Java) members are accessible within the same package.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['access specifiers', 'public', 'private', 'protected', 'encapsulation'],
    examples: [],
    constraints: [],
    hints: ['Think of access specifiers as security levels for class members'],
    companies: ['Amazon', 'Microsoft', 'Infosys', 'TCS'],
    leetcodeLink: '',
  },
  {
    title: 'What is the difference between Composition and Aggregation?',
    description: 'Composition is a strong "part-of" relationship where the child cannot exist without the parent (e.g., Engine in a Car — if Car is destroyed, Engine is too). Aggregation is a weak association where the child can exist independently (e.g., Student in a University — Student exists even if University closes).',
    topic: 'OOP',
    difficulty: 'Medium',
    tags: ['composition', 'aggregation', 'relationship', 'OOP'],
    examples: [{ input: 'Car has Engine (Composition) vs University has Student (Aggregation)', output: 'Engine dies with Car, Student survives without University', explanation: 'Composition = strong, Aggregation = weak relationship' }],
    constraints: [],
    hints: ['Composition = cannot exist without parent, Aggregation = can exist independently'],
    companies: ['Google', 'Amazon', 'Microsoft'],
    leetcodeLink: '',
  },
  {
    title: 'What is the SOLID Principle?',
    description: 'SOLID is a set of 5 design principles for writing maintainable, scalable OOP code. S = Single Responsibility (a class should do one thing), O = Open/Closed (open for extension, closed for modification), L = Liskov Substitution (subclasses should replace parent without breaking), I = Interface Segregation (prefer small interfaces), D = Dependency Inversion (depend on abstractions).',
    topic: 'OOP',
    difficulty: 'Hard',
    tags: ['SOLID', 'design principles', 'architecture', 'clean code'],
    examples: [],
    constraints: [],
    hints: ['SOLID stands for Single, Open/Closed, Liskov, Interface, Dependency'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta', 'Netflix'],
    leetcodeLink: '',
  },
  {
    title: 'What is the Diamond Problem in Inheritance?',
    description: 'The diamond problem occurs when two parent classes inherit from a common grandparent, and a child class inherits both parents. This creates ambiguity about which version of the grandparent method to use. C++ solves it using virtual inheritance. Java avoids it entirely by not allowing multiple class inheritance (only interface inheritance).',
    topic: 'OOP',
    difficulty: 'Hard',
    tags: ['diamond problem', 'multiple inheritance', 'C++', 'Java', 'ambiguity'],
    examples: [{ input: 'A -> B, A -> C, B+C -> D', output: 'Ambiguity: which A method does D inherit?', explanation: 'Two paths to same grandparent cause conflict' }],
    constraints: [],
    hints: ['C++ uses virtual inheritance, Java uses interfaces to avoid this'],
    companies: ['Google', 'Microsoft', 'Samsung'],
    leetcodeLink: '',
  },
  {
    title: 'What is Garbage Collection in OOP?',
    description: 'Garbage collection is automatic memory management that reclaims memory from unused objects. Java has a built-in garbage collector that prevents memory leaks. The JVM detects unreachable objects and frees their memory. Common GC algorithms include Mark and Sweep, G1, and CMS. You can request GC via System.gc() but execution is not guaranteed.',
    topic: 'OOP',
    difficulty: 'Medium',
    tags: ['garbage collection', 'memory management', 'Java', 'JVM'],
    examples: [],
    constraints: [],
    hints: ['GC runs automatically but you can suggest it with System.gc()'],
    companies: ['Amazon', 'Microsoft', 'Google', 'Flipkart'],
    leetcodeLink: '',
  },
  {
    title: 'What is a Virtual Function?',
    description: 'A virtual function is declared in the base class and overridden in the derived class using the virtual keyword in C++. It enables runtime polymorphism (dynamic dispatch). When a virtual function is called through a base class pointer, the derived class version is executed. A pure virtual function (= 0) makes the class abstract.',
    topic: 'OOP',
    difficulty: 'Medium',
    tags: ['virtual function', 'runtime polymorphism', 'C++', 'dynamic dispatch'],
    examples: [{ input: 'virtual void draw() called on Base*', output: 'Calls Derived::draw() at runtime', explanation: 'Virtual function resolves to actual object type at runtime' }],
    constraints: [],
    hints: ['virtual keyword enables late binding in C++'],
    companies: ['Microsoft', 'Google', 'Samsung', 'Qualcomm'],
    leetcodeLink: '',
  },
  {
    title: 'What is Early Binding vs Late Binding?',
    description: 'Early Binding (Static): Method call is resolved at compile time, used in method overloading. Late Binding (Dynamic): Method call is resolved at runtime based on the actual object type, used in method overriding. Late binding enables polymorphism and is achieved using virtual functions in C++ and interfaces/inheritance in Java.',
    topic: 'OOP',
    difficulty: 'Medium',
    tags: ['early binding', 'late binding', 'compile time', 'runtime', 'polymorphism'],
    examples: [],
    constraints: [],
    hints: ['Overloading = early binding, Overriding = late binding'],
    companies: ['Google', 'Microsoft', 'Amazon'],
    leetcodeLink: '',
  },
  {
    title: 'What is Object Cloning? Shallow vs Deep Copy?',
    description: 'Object cloning creates an exact copy of an object. In Java, the clone() method from the Cloneable interface is used. Shallow copy copies only references to objects (not the objects themselves), so changes in the copy affect the original. Deep copy copies the entire object graph, creating independent copies of all nested objects.',
    topic: 'OOP',
    difficulty: 'Medium',
    tags: ['cloning', 'shallow copy', 'deep copy', 'Java'],
    examples: [{ input: 'Shallow copy of object with nested list', output: 'Changing nested list in copy also changes original', explanation: 'Shallow copy shares references, deep copy does not' }],
    constraints: [],
    hints: ['Shallow = copy references, Deep = copy actual objects'],
    companies: ['Amazon', 'Microsoft', 'Google'],
    leetcodeLink: '',
  },

  // ==================== DSA QUESTIONS ====================

  {
    title: 'What is a Data Structure?',
    description: 'A data structure is a way to organize, store, and manage data efficiently so it can be accessed and modified easily. Different data structures are suited for different kinds of applications. Examples include Arrays, Linked Lists, Stacks, Queues, Trees, and Graphs. Choosing the right data structure can drastically improve performance.',
    topic: 'Arrays',
    difficulty: 'Easy',
    tags: ['data structure', 'basics', 'fundamentals'],
    examples: [],
    constraints: [],
    hints: ['Think about how data is organized and accessed in each structure'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Infosys', 'TCS'],
    leetcodeLink: '',
  },
  {
    title: 'What is the difference between Array and Linked List?',
    description: 'An Array stores elements contiguously in memory with fast index-based access (O(1)), but insertion and deletion are expensive (O(n)). A Linked List stores elements as nodes connected by pointers with dynamic size and efficient insertion/deletion (O(1) at head), but slow access (O(n)). Arrays are better for random access, linked lists for frequent insertions.',
    topic: 'Arrays',
    difficulty: 'Easy',
    tags: ['array', 'linked list', 'comparison', 'memory'],
    examples: [{ input: 'Access element at index 5', output: 'Array: O(1), Linked List: O(n)', explanation: 'Array uses index arithmetic, linked list must traverse' }],
    constraints: [],
    hints: ['Array = contiguous memory, Linked List = scattered nodes with pointers'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta'],
    leetcodeLink: '',
  },
  {
    title: 'How does a Stack work?',
    description: 'A Stack follows the LIFO (Last In, First Out) principle. The main operations are push() to add an element, pop() to remove the top element, and peek() to view the top without removing it. Stacks are used in undo mechanisms, recursion call stacks, expression parsing, and backtracking algorithms.',
    topic: 'Stacks & Queues',
    difficulty: 'Easy',
    tags: ['stack', 'LIFO', 'push', 'pop'],
    examples: [{ input: 'Push 1, 2, 3 then pop', output: '3 (last in, first out)', explanation: 'LIFO means last pushed element is popped first' }],
    constraints: [],
    hints: ['Think of a stack of plates — you add and remove from the top'],
    companies: ['Amazon', 'Microsoft', 'Infosys'],
    leetcodeLink: '',
  },
  {
    title: 'What is a Queue? Difference between Queue and Deque?',
    description: 'A Queue follows FIFO (First In, First Out) principle. Elements are added at the rear and removed from the front. A Deque (Double-Ended Queue) allows insertion and removal from both ends. Queues are used in scheduling, caching, and BFS traversal. Deques are useful for sliding window problems.',
    topic: 'Stacks & Queues',
    difficulty: 'Easy',
    tags: ['queue', 'FIFO', 'deque', 'BFS'],
    examples: [{ input: 'Enqueue 1, 2, 3 then dequeue', output: '1 (first in, first out)', explanation: 'FIFO means first enqueued element is dequeued first' }],
    constraints: [],
    hints: ['Think of a queue at a bus stop — first person in line boards first'],
    companies: ['Amazon', 'Microsoft', 'Google'],
    leetcodeLink: '',
  },
  {
    title: 'What is a Priority Queue?',
    description: 'A Priority Queue is a type of queue where each element has a priority value. Higher priority elements are dequeued before lower priority ones regardless of insertion order. It is typically implemented using a heap data structure. Priority queues are used in Dijkstra\'s algorithm, scheduling, and event-driven simulation.',
    topic: 'Heaps',
    difficulty: 'Medium',
    tags: ['priority queue', 'heap', 'scheduling'],
    examples: [{ input: 'Insert (task1, priority=3), (task2, priority=1)', output: 'task2 is dequeued first (higher priority = lower number)', explanation: 'Min-heap based priority queue serves lowest priority number first' }],
    constraints: [],
    hints: ['Priority queues are usually implemented using min-heaps or max-heaps'],
    companies: ['Google', 'Amazon', 'Microsoft'],
    leetcodeLink: '',
  },
  {
    title: 'What is a Hash Table and how does it work?',
    description: 'A Hash Table maps keys to values using a hash function that converts keys into array indices. It allows O(1) average-case lookup, insert, and delete operations. Collisions (when two keys hash to the same index) are handled using chaining (linked list at each bucket) or open addressing (probing for next empty slot).',
    topic: 'Hashing',
    difficulty: 'Medium',
    tags: ['hash table', 'hash function', 'collision', 'chaining'],
    examples: [{ input: 'key = "name", value = "Alice"', output: 'hash("name") = 42, store at index 42', explanation: 'Hash function maps key to array index for O(1) access' }],
    constraints: [],
    hints: ['Hash function converts key to index, collision handling manages duplicate indices'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta'],
    leetcodeLink: '',
  },
  {
    title: 'What is a Binary Search Tree (BST)?',
    description: 'A Binary Search Tree is a binary tree where for every node, all values in the left subtree are less than the node, and all values in the right subtree are greater. This property enables fast lookup, insert, and delete in O(log n) average case. An unbalanced BST can degrade to O(n) for these operations.',
    topic: 'Trees',
    difficulty: 'Medium',
    tags: ['BST', 'binary tree', 'search', 'O(log n)'],
    examples: [{ input: 'Search for 7 in BST', output: 'Go right if target > node, left if target < node', explanation: 'BST property halves the search space at each node' }],
    constraints: [],
    hints: ['Left < Node < Right is the key BST property'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Flipkart'],
    leetcodeLink: '',
  },
  {
    title: 'What is the difference between BFS and DFS?',
    description: 'BFS (Breadth-First Search) explores all neighbors at the current level before moving to the next level. It uses a queue and is good for finding the shortest path. DFS (Depth-First Search) explores as far as possible along each branch before backtracking. It uses a stack or recursion and is good for cycle detection and topological sorting.',
    topic: 'Graphs',
    difficulty: 'Medium',
    tags: ['BFS', 'DFS', 'graph traversal', 'queue', 'stack'],
    examples: [{ input: 'Graph: A-B-C-D (linear)', output: 'BFS: A,B,C,D | DFS: A,B,C,D (same for linear)', explanation: 'Difference shows in branching graphs where BFS goes wide, DFS goes deep' }],
    constraints: [],
    hints: ['BFS uses queue (level by level), DFS uses stack (depth first)'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta', 'LinkedIn'],
    leetcodeLink: '',
  },
  {
    title: 'What is a Heap data structure?',
    description: 'A Heap is a complete binary tree that satisfies the heap property. In a Max-Heap, every parent node is greater than or equal to its children. In a Min-Heap, every parent is less than or equal to its children. Heaps support O(log n) insert and delete. They are used in priority queues and heap sort.',
    topic: 'Heaps',
    difficulty: 'Medium',
    tags: ['heap', 'max-heap', 'min-heap', 'binary tree'],
    examples: [{ input: 'Min-Heap with elements [3,1,6,5,2,4]', output: 'Root = 1 (minimum element)', explanation: 'Min-heap always keeps minimum at root' }],
    constraints: [],
    hints: ['Heap is always a complete binary tree with parent-child ordering'],
    companies: ['Google', 'Amazon', 'Microsoft'],
    leetcodeLink: '',
  },
  {
    title: 'What is a Trie data structure?',
    description: 'A Trie is a tree-like data structure used to store strings where each node represents a character. It enables efficient string retrieval and prefix matching. Insert and search operations run in O(m) where m is the string length. Tries are used in autocomplete features, spell checkers, and IP routing.',
    topic: 'Trees',
    difficulty: 'Hard',
    tags: ['trie', 'prefix tree', 'string', 'autocomplete'],
    examples: [{ input: 'Insert "apple", search "app"', output: 'Found — "app" is a prefix of "apple"', explanation: 'Trie stores characters as nodes along the path' }],
    constraints: [],
    hints: ['Each path from root to a node represents a prefix or word'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Uber'],
    leetcodeLink: '',
  },
  {
    title: 'What is Dynamic Programming?',
    description: 'Dynamic Programming is an optimization technique that solves complex problems by breaking them into overlapping subproblems and storing their results to avoid redundant calculations. There are two approaches: Memoization (top-down with recursion and caching) and Tabulation (bottom-up with iteration). DP is used in Fibonacci, knapsack, LCS, and many other problems.',
    topic: 'Dynamic Programming',
    difficulty: 'Medium',
    tags: ['dynamic programming', 'memoization', 'tabulation', 'optimization'],
    examples: [{ input: 'Fibonacci(5)', output: '5', explanation: 'DP stores fib(2), fib(3), fib(4) to avoid recalculation' }],
    constraints: [],
    hints: ['If a problem has overlapping subproblems and optimal substructure, use DP'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta', 'Apple'],
    leetcodeLink: '',
  },
  {
    title: 'What is the Sliding Window Technique?',
    description: 'The sliding window technique is an optimization method to reduce time complexity in problems involving subarrays or substrings. Instead of recomputing from scratch, you maintain a window of elements and slide it by adding the new element and removing the old one. It reduces O(n²) solutions to O(n).',
    topic: 'Arrays',
    difficulty: 'Medium',
    tags: ['sliding window', 'array', 'string', 'optimization'],
    examples: [{ input: 'Find max sum of k consecutive elements in [2,3,4,1,5]', output: '8 (subarray [3,4,1] or [4,1,5]?)', explanation: 'Slide window of size k, update sum by adding new and removing old element' }],
    constraints: [],
    hints: ['Maintain a window and slide it instead of restarting from scratch'],
    companies: ['Amazon', 'Microsoft', 'Google', 'Flipkart'],
    leetcodeLink: '',
  },
  {
    title: 'Explain the Two-Pointer Technique',
    description: 'The two-pointer technique uses two indices to traverse a data structure, usually from opposite ends or in the same direction. It is helpful for searching pairs, reversing sequences, or partitioning arrays efficiently. Common problems solved include Two Sum in sorted arrays, palindrome checking, and removing duplicates.',
    topic: 'Arrays',
    difficulty: 'Medium',
    tags: ['two pointer', 'array', 'sorted', 'optimization'],
    examples: [{ input: 'Sorted array [1,2,3,4,5], target=6', output: 'Pair (1,5) — pointers from both ends', explanation: 'Move left pointer right if sum too small, right pointer left if too large' }],
    constraints: [],
    hints: ['Works best on sorted arrays; use when you need to find pairs'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta'],
    leetcodeLink: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',
  },
  {
    title: 'What is Binary Search Algorithm?',
    description: 'Binary Search is an efficient algorithm to find an element in a sorted array by repeatedly dividing the search range in half. At each step, it compares the target with the middle element and eliminates half the array. Time complexity is O(log n). Binary search can only be applied on sorted data.',
    topic: 'Sorting & Searching',
    difficulty: 'Easy',
    tags: ['binary search', 'sorted array', 'O(log n)'],
    examples: [{ input: 'Sorted array [1,3,5,7,9], target=7', output: 'Index 3', explanation: 'Check mid=5, target>5 so search right half, mid=7 found' }],
    constraints: ['Array must be sorted'],
    hints: ['Always check if input is sorted before applying binary search'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta', 'Apple'],
    leetcodeLink: 'https://leetcode.com/problems/binary-search/',
  },
  {
    title: 'What is Merge Sort Algorithm?',
    description: 'Merge Sort is a divide-and-conquer sorting algorithm. It recursively splits the array into halves, sorts each half, and then merges them back together. Time complexity is O(n log n) in all cases. It is a stable sort (preserves order of equal elements) but requires O(n) extra space for merging.',
    topic: 'Sorting & Searching',
    difficulty: 'Medium',
    tags: ['merge sort', 'divide and conquer', 'sorting', 'stable sort'],
    examples: [{ input: '[5,3,1,4,2]', output: '[1,2,3,4,5]', explanation: 'Split into [5,3,1] and [4,2], sort each, merge' }],
    constraints: [],
    hints: ['Split until single elements, then merge back in sorted order'],
    companies: ['Google', 'Amazon', 'Microsoft'],
    leetcodeLink: 'https://leetcode.com/problems/sort-an-array/',
  },
  {
    title: 'What is Quick Sort Algorithm?',
    description: 'Quick Sort chooses a pivot element, partitions the array so elements less than pivot are on the left and greater are on the right, then recursively sorts both halves. Average time complexity is O(n log n) but worst case is O(n²) with poor pivot choice. It is not stable but works in-place using O(log n) space.',
    topic: 'Sorting & Searching',
    difficulty: 'Medium',
    tags: ['quick sort', 'pivot', 'partition', 'divide and conquer'],
    examples: [{ input: '[5,3,1,4,2], pivot=3', output: '[1,2] pivot [4,5] → [1,2,3,4,5]', explanation: 'Elements < pivot go left, elements > pivot go right' }],
    constraints: [],
    hints: ['Pivot selection affects performance — random pivot avoids worst case'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta'],
    leetcodeLink: 'https://leetcode.com/problems/sort-an-array/',
  },
  {
    title: 'What is Backtracking?',
    description: 'Backtracking is a recursive technique used to solve problems by trying all possible paths and undoing (backtracking) if a solution path fails. It is essentially a depth-first search with pruning. Common examples include N-Queens, Sudoku Solver, generating all subsets and permutations, and the rat in a maze problem.',
    topic: 'Recursion',
    difficulty: 'Hard',
    tags: ['backtracking', 'recursion', 'DFS', 'N-Queens'],
    examples: [{ input: 'N-Queens: place 4 queens on 4x4 board', output: 'Two valid configurations', explanation: 'Try each column, backtrack if queens attack each other' }],
    constraints: [],
    hints: ['Try a choice, recurse, undo if it leads to failure'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta'],
    leetcodeLink: 'https://leetcode.com/problems/n-queens/',
  },
  {
    title: "What is Kadane's Algorithm?",
    description: "Kadane's Algorithm finds the maximum subarray sum in an array in O(n) time. It maintains a running current sum and resets it to the current element if it becomes negative. The maximum of all current sums is tracked as the answer. It handles arrays with all negative numbers by starting with the first element.",
    topic: 'Dynamic Programming',
    difficulty: 'Medium',
    tags: ["Kadane's", 'maximum subarray', 'dynamic programming'],
    examples: [{ input: '[-2,1,-3,4,-1,2,1,-5,4]', output: '6 (subarray [4,-1,2,1])', explanation: 'Running sum resets when it goes negative, track maximum seen' }],
    constraints: [],
    hints: ['Reset current sum to current element when current sum becomes negative'],
    companies: ['Amazon', 'Microsoft', 'Google', 'Paytm'],
    leetcodeLink: 'https://leetcode.com/problems/maximum-subarray/',
  },
  {
    title: "What is Floyd's Cycle Detection Algorithm?",
    description: "Floyd's Cycle Detection Algorithm (Tortoise and Hare) is used to detect loops in linked lists. Two pointers move at different speeds — slow pointer moves one step, fast pointer moves two steps. If they meet, a cycle exists. To find the cycle start, reset one pointer to head and move both one step until they meet again.",
    topic: 'Linked Lists',
    difficulty: 'Medium',
    tags: ["Floyd's algorithm", 'cycle detection', 'linked list', 'two pointers'],
    examples: [{ input: 'Linked list: 1->2->3->4->2 (cycle)', output: 'Cycle detected, starts at node 2', explanation: 'Slow and fast pointers meet inside the cycle' }],
    constraints: [],
    hints: ['If slow and fast meet, there is a cycle — then find the entry point'],
    companies: ['Amazon', 'Microsoft', 'Google', 'Flipkart'],
    leetcodeLink: 'https://leetcode.com/problems/linked-list-cycle/',
  },
  {
    title: "What is Dijkstra's Algorithm?",
    description: "Dijkstra's Algorithm finds the shortest path from a source node to all other nodes in a weighted graph with non-negative edge weights. It uses a priority queue (min-heap) to always expand the closest unvisited node. Time complexity is O(V + E log V). It cannot handle negative weight edges.",
    topic: 'Graphs',
    difficulty: 'Hard',
    tags: ["Dijkstra's", 'shortest path', 'graph', 'priority queue'],
    examples: [{ input: 'Graph with nodes A,B,C and weights, source=A', output: 'Shortest distances from A to all nodes', explanation: 'Always expand nearest unvisited node greedily' }],
    constraints: ['Non-negative edge weights only'],
    hints: ['Use a min-heap to efficiently get the closest unvisited node'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Uber', 'Lyft'],
    leetcodeLink: 'https://leetcode.com/problems/network-delay-time/',
  },
  {
    title: 'What is Topological Sorting?',
    description: 'Topological Sorting gives a linear ordering of vertices in a Directed Acyclic Graph (DAG) such that for every directed edge u → v, vertex u comes before vertex v. It is used in task scheduling, build systems, and dependency resolution. Algorithms include DFS-based approach and Kahn\'s algorithm (BFS-based).',
    topic: 'Graphs',
    difficulty: 'Hard',
    tags: ['topological sort', 'DAG', 'graph', 'scheduling'],
    examples: [{ input: 'Course prerequisites: A->B->C', output: 'Topological order: A, B, C', explanation: 'Must take A before B, and B before C' }],
    constraints: ['Graph must be a DAG (no cycles)'],
    hints: ['DFS-based: add node to result after all its dependencies are processed'],
    companies: ['Google', 'Amazon', 'Microsoft'],
    leetcodeLink: 'https://leetcode.com/problems/course-schedule/',
  },
  {
    title: 'What is Big-O Notation?',
    description: 'Big-O notation expresses time or space complexity in terms of input size n, describing the upper bound of growth rate. O(1) is constant time, O(log n) is logarithmic, O(n) is linear, O(n log n) is log-linear, O(n²) is quadratic. Big-O helps compare algorithm efficiency and scalability.',
    topic: 'Sorting & Searching',
    difficulty: 'Easy',
    tags: ['Big-O', 'time complexity', 'space complexity', 'algorithm analysis'],
    examples: [{ input: 'Linear search on n elements', output: 'O(n) time complexity', explanation: 'In worst case must check all n elements' }],
    constraints: [],
    hints: ['Big-O describes worst case behavior as input grows'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta', 'Apple'],
    leetcodeLink: '',
  },
  {
    title: 'What is the Longest Common Subsequence (LCS)?',
    description: 'LCS is the longest sequence that appears in the same relative order in both strings but not necessarily contiguously. For example, LCS of "ABCBDAB" and "BDCAB" is "BCAB" of length 4. It is solved using dynamic programming in O(m×n) time and space. LCS is used in diff tools and DNA sequence alignment.',
    topic: 'Dynamic Programming',
    difficulty: 'Hard',
    tags: ['LCS', 'dynamic programming', 'string', 'subsequence'],
    examples: [{ input: '"ABCBDAB" and "BDCAB"', output: 'LCS length = 4 ("BCAB")', explanation: 'DP table fills bottom-up comparing characters' }],
    constraints: [],
    hints: ['If characters match, LCS(i,j) = 1 + LCS(i-1,j-1), else max(LCS(i-1,j), LCS(i,j-1))'],
    companies: ['Google', 'Amazon', 'Microsoft'],
    leetcodeLink: 'https://leetcode.com/problems/longest-common-subsequence/',
  },

  // ==================== CODING INTERVIEW QUESTIONS ====================

  {
    title: 'How does a HashMap work internally?',
    description: 'A HashMap uses a hash function to convert keys into array indices. Each index points to a bucket that stores key-value pairs. When two keys hash to the same index (collision), it is handled by chaining (linked list at each bucket) or open addressing. Java 8+ uses a balanced tree (red-black tree) when a bucket exceeds 8 entries.',
    topic: 'Hashing',
    difficulty: 'Medium',
    tags: ['HashMap', 'hash function', 'collision', 'internal working'],
    examples: [{ input: 'map.put("name", "Alice")', output: 'Stored at hash("name") % capacity index', explanation: 'Hash function maps key to bucket index for O(1) average access' }],
    constraints: [],
    hints: ['Load factor determines when to resize the hash table'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta', 'Flipkart'],
    leetcodeLink: '',
  },
  {
    title: 'Find the Longest Substring Without Repeating Characters',
    description: 'Given a string, find the length of the longest substring without repeating characters. Use the sliding window technique with a set to track characters in the current window. When a duplicate is found, shrink the window from the left until the duplicate is removed. Time complexity is O(n).',
    topic: 'Strings',
    difficulty: 'Medium',
    tags: ['sliding window', 'string', 'set', 'substring'],
    examples: [{ input: '"abcabcbb"', output: '3 (substring "abc")', explanation: 'Window expands right, shrinks left when duplicate found' }],
    constraints: ['0 <= s.length <= 5 * 10^4'],
    hints: ['Use a set to track characters in current window, move left pointer on duplicate'],
    companies: ['Amazon', 'Microsoft', 'Google', 'Meta', 'Adobe'],
    leetcodeLink: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
  },
  {
    title: 'Detect Cycle in a Linked List',
    description: 'Given a linked list, determine if it has a cycle using Floyd\'s Tortoise and Hare algorithm. Move a slow pointer one step and a fast pointer two steps at a time. If they meet, a cycle exists. To find the cycle start, reset one pointer to head and move both one step at a time until they meet.',
    topic: 'Linked Lists',
    difficulty: 'Easy',
    tags: ['linked list', 'cycle', 'two pointers', "Floyd's algorithm"],
    examples: [{ input: '1->2->3->4->2 (cycle at 2)', output: 'true', explanation: 'Slow and fast pointers will eventually meet inside cycle' }],
    constraints: [],
    hints: ['If fast pointer reaches null, no cycle exists'],
    companies: ['Amazon', 'Microsoft', 'Google', 'Adobe'],
    leetcodeLink: 'https://leetcode.com/problems/linked-list-cycle/',
  },
  {
    title: 'Find the Intersection of Two Arrays',
    description: 'Given two arrays, find their intersection (common elements). Use a HashSet to store elements of the first array, then iterate through the second array checking for membership. This achieves O(n + m) time complexity and O(min(n, m)) space complexity. Handle duplicates based on problem requirements.',
    topic: 'Hashing',
    difficulty: 'Easy',
    tags: ['array', 'hashset', 'intersection', 'set'],
    examples: [{ input: 'nums1 = [1,2,2,1], nums2 = [2,2]', output: '[2]', explanation: 'Store nums1 in set, check nums2 elements against it' }],
    constraints: [],
    hints: ['Use HashSet for O(1) lookup of elements'],
    companies: ['Amazon', 'Microsoft', 'Facebook'],
    leetcodeLink: 'https://leetcode.com/problems/intersection-of-two-arrays/',
  },
  {
    title: 'Reverse a Linked List',
    description: 'Reverse a singly linked list in-place. Use three pointers: prev (initially null), curr (initially head), and next. Iterate through the list, reversing each link by setting curr.next = prev, then advancing all three pointers. Time complexity is O(n) and space complexity is O(1).',
    topic: 'Linked Lists',
    difficulty: 'Easy',
    tags: ['linked list', 'reverse', 'three pointers'],
    examples: [{ input: '1->2->3->4->5', output: '5->4->3->2->1', explanation: 'Reverse each pointer direction while traversing' }],
    constraints: [],
    hints: ['Keep track of prev, curr, and next pointers to avoid losing nodes'],
    companies: ['Amazon', 'Microsoft', 'Google', 'Apple'],
    leetcodeLink: 'https://leetcode.com/problems/reverse-linked-list/',
  },
  {
    title: 'Check if a String is a Palindrome',
    description: 'Given a string, determine if it is a palindrome (reads the same forwards and backwards). Use two pointers starting from both ends, comparing characters and moving inward. If any characters don\'t match, return false. Optionally ignore non-alphanumeric characters and case for real-world variants.',
    topic: 'Strings',
    difficulty: 'Easy',
    tags: ['palindrome', 'two pointers', 'string'],
    examples: [{ input: '"racecar"', output: 'true', explanation: 'r=r, a=a, c=c, middle e, all characters match from both ends' }],
    constraints: [],
    hints: ['Use two pointers from start and end moving inward'],
    companies: ['Amazon', 'Microsoft', 'Google', 'Adobe'],
    leetcodeLink: 'https://leetcode.com/problems/valid-palindrome/',
  },
  {
    title: 'Implement LRU Cache',
    description: 'Design an LRU (Least Recently Used) Cache that supports O(1) get and put operations. Use a combination of a HashMap and Doubly Linked List. The HashMap stores key-to-node mappings for O(1) access. The doubly linked list maintains access order — most recently used at head, least recently used at tail.',
    topic: 'Hashing',
    difficulty: 'Hard',
    tags: ['LRU cache', 'hashmap', 'doubly linked list', 'design'],
    examples: [{ input: 'capacity=2, put(1,1), put(2,2), get(1), put(3,3)', output: 'get(2) returns -1 (evicted), get(3) returns 3', explanation: 'Key 2 was LRU when key 3 was inserted' }],
    constraints: ['1 <= capacity <= 3000'],
    hints: ['HashMap for O(1) lookup, doubly linked list for O(1) insertion/deletion'],
    companies: ['Amazon', 'Microsoft', 'Google', 'Meta', 'Uber'],
    leetcodeLink: 'https://leetcode.com/problems/lru-cache/',
  },
  {
    title: 'Find Kth Largest Element in an Array',
    description: 'Find the kth largest element in an unsorted array. The most efficient approach uses a min-heap of size k. Iterate through the array, maintaining only the k largest elements in the heap. The root of the heap (minimum of the heap) is the kth largest element. Time complexity is O(n log k).',
    topic: 'Heaps',
    difficulty: 'Medium',
    tags: ['heap', 'kth largest', 'priority queue'],
    examples: [{ input: 'nums = [3,2,1,5,6,4], k = 2', output: '5', explanation: 'Min-heap of size 2 keeps [5,6], root is 5 (2nd largest)' }],
    constraints: ['1 <= k <= nums.length'],
    hints: ['Min-heap of size k: if new element > heap root, replace root and heapify'],
    companies: ['Amazon', 'Microsoft', 'Google', 'Meta'],
    leetcodeLink: 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
  },
  {
    title: 'Solve the 0/1 Knapsack Problem',
    description: 'Given weights and values of n items and a knapsack of capacity W, find the maximum value you can carry. Each item can be taken at most once (0/1 choice). Use dynamic programming where dp[i][w] represents the maximum value using first i items with capacity w. Time complexity is O(n×W).',
    topic: 'Dynamic Programming',
    difficulty: 'Hard',
    tags: ['knapsack', 'dynamic programming', 'optimization'],
    examples: [{ input: 'weights=[1,3,4,5], values=[1,4,5,7], W=7', output: '9 (items with weights 3 and 4)', explanation: 'dp table builds up from smaller subproblems' }],
    constraints: [],
    hints: ['dp[i][w] = max(dp[i-1][w], val[i] + dp[i-1][w-wt[i]]) if wt[i] <= w'],
    companies: ['Amazon', 'Microsoft', 'Google'],
    leetcodeLink: 'https://leetcode.com/problems/partition-equal-subset-sum/',
  },
  {
    title: 'Find Duplicate Numbers in an Array',
    description: 'Given an array of integers, find all elements that appear more than once. Use a HashSet to track seen elements — if an element is already in the set when encountered, it is a duplicate. Time complexity is O(n) and space complexity is O(n). Alternative: sort the array and check adjacent elements.',
    topic: 'Arrays',
    difficulty: 'Easy',
    tags: ['array', 'duplicates', 'hashset'],
    examples: [{ input: '[4,3,2,7,8,2,3,1]', output: '[2,3]', explanation: '2 and 3 appear twice in the array' }],
    constraints: [],
    hints: ['Use a set to track seen numbers; add to result on second encounter'],
    companies: ['Amazon', 'Microsoft', 'Google'],
    leetcodeLink: 'https://leetcode.com/problems/find-all-duplicates-in-an-array/',
  },
  {
    title: 'Implement Stack using Queues',
    description: 'Implement a stack (LIFO) data structure using only queue operations. When pushing a new element, add it to the queue then rotate all previous elements behind it by dequeuing and re-enqueuing them. This makes pop() and top() O(1) but push() O(n). Alternatively, make pop() O(n) and push() O(1).',
    topic: 'Stacks & Queues',
    difficulty: 'Medium',
    tags: ['stack', 'queue', 'design', 'LIFO'],
    examples: [{ input: 'push(1), push(2), top()', output: '2', explanation: 'After rotation, newest element is always at front of queue' }],
    constraints: [],
    hints: ['After each push, rotate all older elements to be behind the new element'],
    companies: ['Amazon', 'Microsoft', 'Google'],
    leetcodeLink: 'https://leetcode.com/problems/implement-stack-using-queues/',
  },
  {
    title: 'What is the difference between Multithreading and Multiprocessing?',
    description: 'Multithreading runs multiple threads within a single process, sharing the same memory space. It is lighter weight but less isolated. Multiprocessing runs multiple processes each with their own memory space, providing better isolation and true parallelism. In Python, multithreading is limited by the GIL while multiprocessing bypasses it.',
    topic: 'OS',
    difficulty: 'Medium',
    tags: ['multithreading', 'multiprocessing', 'concurrency', 'parallelism'],
    examples: [],
    constraints: [],
    hints: ['Threads share memory (faster but risky), processes have separate memory (safer but heavier)'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta'],
    leetcodeLink: '',
  },
  {
    title: 'What are Lambda Functions?',
    description: 'Lambda functions are anonymous (unnamed) functions defined inline for short operations. In Python, syntax is lambda x: x + 2. In Java (introduced in Java 8), they enable functional programming with syntax like (x) -> x + 2. Lambda functions are commonly used with map(), filter(), and sort() operations.',
    topic: 'OOP',
    difficulty: 'Easy',
    tags: ['lambda', 'anonymous function', 'functional programming', 'Java', 'Python'],
    examples: [{ input: 'sorted(list, key=lambda x: x[1])', output: 'List sorted by second element', explanation: 'Lambda provides a quick inline sorting key function' }],
    constraints: [],
    hints: ['Lambda = anonymous function for simple one-liner operations'],
    companies: ['Amazon', 'Google', 'Microsoft'],
    leetcodeLink: '',
  },
  {
    title: 'What are Function Closures?',
    description: 'A closure is a function that remembers and can access variables from its outer (enclosing) scope even after the outer function has finished executing. Closures are widely used in JavaScript and Python for data encapsulation and creating function factories. They capture the variables by reference, not by value.',
    topic: 'OOP',
    difficulty: 'Medium',
    tags: ['closure', 'scope', 'Python', 'JavaScript', 'functional programming'],
    examples: [{ input: 'outer(5) returns inner function', output: 'add5(3) returns 8', explanation: 'inner function remembers x=5 from outer function scope' }],
    constraints: [],
    hints: ['Closures capture variables from enclosing scope by reference'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta'],
    leetcodeLink: '',
  },
];

async function main() {
  console.log('🔌 Connecting to MongoDB...');
  await mongoose.connect(MONGODB_URI);
  console.log('✅ Connected!\n');

  console.log(`📦 Inserting ${questions.length} questions...`);
  await Question.insertMany(questions, { ordered: false });

  const total = await Question.countDocuments();
  console.log(`\n🎉 Done! Total questions in database: ${total}`);
  await mongoose.disconnect();
}

main().catch(err => {
  console.error('Fatal error:', err);
  mongoose.disconnect();
  process.exit(1);
});